# Загрузка датасета

In [7]:
import pandas as pd

df = pd.read_csv('../data/HouseData.csv')

In [4]:
df.head()

,Unnamed: 0,district,price,address,AdUpdateDate,Category,GrossSquareMeters,BuildingAge,NumberFloorsofBuilding,UsingStatus,...,PriceStatus,RentalIncome,NumberOfBalconies,BalconyType,HallSquareMeters,WCSquareMeters,IsItVideoNavigable?,Subscription,BathroomSquareMeters,BalconySquareMeters
0,0,adalar,"3,100,000TL","['Anasayfa', 'Satılık Daire', 'İstanbul Satılı...",24 Şubat 2022,Satılık,160 m2,21 Ve Üzeri,3,Mülk Sahibi Oturuyor,...,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,adalar,"1,600,000TL","['Anasayfa', 'Satılık Daire', 'İstanbul Satılı...",02 Mart 2022,Satılık,120 m2,5-10,3,Mülk Sahibi Oturuyor,...,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,adalar,"18,500,000TL","['Anasayfa', 'Satılık Müstakil Ev', 'İstanbul ...",11 Şubat 2022,Satılık,350 m2,21 Ve Üzeri,2,Mülk Sahibi Oturuyor,...,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,adalar,"9,500,000TL","['Anasayfa', 'Satılık Bina', 'İstanbul Satılık...",11 Şubat 2022,Satılık,550 m2,11-15,3,Mülk Sahibi Oturuyor,...,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,adalar,"25,000,000TL","['Anasayfa', 'Satılık Köşk', 'İstanbul Satılık...",19 Ocak 2022,Satılık,840 m2,21 Ve Üzeri,4,Boş,...,Genel Fiyat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.dtypes

Unnamed: 0                   int64
district                    object
price                       object
address                     object
AdUpdateDate                object
Category                    object
GrossSquareMeters           object
BuildingAge                 object
NumberFloorsofBuilding       int64
UsingStatus                 object
EligibilityForInvestment    object
BuildStatus                 object
TitleStatus                 object
ItemStatus                  object
NumberOfBathrooms           object
NumberOfWCs                 object
AdCreationDate              object
Type                        object
NetSquareMeters             object
NumberOfRooms               object
FloorLocation               object
HeatingType                 object
CreditEligibility           object
InsideTheSite               object
StructureType               object
MortgageStatus              object
Swap                        object
Balcony                     object
PriceStatus                 object
RentalIncome                object
NumberOfBalconies           object
BalconyType                 object
HallSquareMeters            object
WCSquareMeters              object
IsItVideoNavigable?         object
Subscription                object
BathroomSquareMeters        object
BalconySquareMeters         object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25155 entries, 0 to 25154
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                25155 non-null  int64
 1   district                  25155 non-null  object
 2   price                     25155 non-null  object
 3   address                   25155 non-null  object
 4   AdUpdateDate              25155 non-null  object
 5   Category                  25155 non-null  object
 6   GrossSquareMeters         25155 non-null  object
 7   BuildingAge               25155 non-null  object
 8   NumberFloorsofBuilding    25155 non-null  int64
 9   UsingStatus               25155 non-null  object
 10  EligibilityForInvestment  21506 non-null  object
 11  BuildStatus               11231 non-null  object
 12  TitleStatus               9712 non-null   object
 13  ItemStatus                18332 non-null  object
 14  NumberOfBathrooms         25155 non-null  object
 15  NumberOfWCs               8129 non-null   object
 16  AdCreationDate            25155 non-null  object
 17  Type                      25155 non-null  object
 18  NetSquareMeters           25155 non-null  object
 19  NumberOfRooms             25155 non-null  object
 20  FloorLocation             25155 non-null  object
 21  HeatingType               25155 non-null  object
 22  CreditEligibility         25155 non-null  object
 23  InsideTheSite             25155 non-null  object
 24  StructureType             10406 non-null  object
 25  MortgageStatus            6058 non-null   object
 26  Swap                      20839 non-null  object
 27  Balcony                   9109 non-null   object
 28  PriceStatus               25155 non-null  object
 29  RentalIncome              5815 non-null   object
 30  NumberOfBalconies         5324 non-null   object
 31  BalconyType               4720 non-null   object
 32  HallSquareMeters          1433 non-null   object
 33  WCSquareMeters            865 non-null    object
 34  IsItVideoNavigable?       5481 non-null   object
 35  Subscription              4488 non-null   object
 36  BathroomSquareMeters      1112 non-null   object
 37  BalconySquareMeters       1040 non-null   object
dtypes: int64(2), object(36)
memory usage: 7.3+ MB

# Оставим только необходимые колонки датасета

In [12]:
columns_to_keep = [
    'NumberOfRooms',
    'GrossSquareMeters',
    'FloorLocation',
    'NumberFloorsofBuilding',
    'BuildStatus',
    'price',
    'district',
    'BuildingAge',
]

df_clean = df[columns_to_keep].copy()

In [13]:
rename_map = {
    'NumberOfRooms': 'rooms',
    'GrossSquareMeters': 'square_gross',
    'FloorLocation': 'floor',
    'NumberFloorsofBuilding': 'total_floors',
    'BuildStatus': 'build_status',
    'price': 'price_tl',
    'district': 'district',
    'BuildingAge': 'building_age',
}

df_clean = df_clean.rename(columns=rename_map)

In [25]:
df_clean['building_age'].unique()

array(['21 Ve Üzeri', '5-10', '11-15', '2', '0 (Yeni)', '3', '4', '16-20',
       '1', '20 Ve Üzeri'], dtype=object)

In [16]:
df_clean.head(50)

,rooms,square_gross,floor,total_floors,build_status,price_tl,district,building_age
0,3+1,160 m2,Çatı Katı,3,NaN,"3,100,000TL",adalar,21 Ve Üzeri
1,2+1,120 m2,Bahçe Katı,3,İkinci El,"1,600,000TL",adalar,5-10
2,3+1,350 m2,Düz Giriş,2,NaN,"18,500,000TL",adalar,21 Ve Üzeri
3,8+ Oda,550 m2,Düz Giriş,3,İkinci El,"9,500,000TL",adalar,11-15
4,8+ Oda,840 m2,Düz Giriş,4,İkinci El,"25,000,000TL",adalar,21 Ve Üzeri
5,3+2,200 m2,Düz Giriş,2,NaN,"7,000,000TL",adalar,21 Ve Üzeri
6,8+ Oda,400 m2,Bahçe Dublex,3,NaN,"3,250,000TL",adalar,21 Ve Üzeri
7,5+1,250 m2,Villa Tipi,2,NaN,"2,850,000TL",adalar,21 Ve Üzeri
8,5+1,360 m2,Düz Giriş,2,NaN,"8,350,000TL",adalar,21 Ve Üzeri
9,5 Oda,180 m2,Düz Giriş,2,NaN,"10,800,000TL",adalar,21 Ve Üzeri
10,2+2,125 m2,1. Kat,3,NaN,"2,200,000TL",adalar,21 Ve Üzeri
11,2+1,140 m2,Düz Giriş,2,NaN,"1,000,000TL",adalar,21 Ve Üzeri
12,7+3,260 m2,Düz Giriş,3,NaN,"8,250,000TL",adalar,21 Ve Üzeri
13,8+ Oda,500 m2,Düz Giriş,2,NaN,"4,885,000TL",adalar,21 Ve Üzeri
14,8+ Oda,430 m2,Villa Tipi,3,İkinci El,"34,550,000TLarrow_downward%3",adalar,21 Ve Üzeri
15,2+1,130 m2,Müstakil,2,İkinci El,"2,915,000TL",adalar,21 Ve Üzeri
16,1+1,75 m2,Bahçe Katı,3,İkinci El,"885,000TL",adalar,21 Ve Üzeri
17,8+ Oda,550 m2,Düz Giriş,3,İkinci El,"9,500,000TL",adalar,11-15
18,5+3,250 m2,Düz Giriş,2,NaN,"2,600,000TL",adalar,21 Ve Üzeri
19,1 Oda,250 m2,Düz Giriş,3,NaN,"3,100,000TL",adalar,21 Ve Üzeri
20,6+1,682 m2,Müstakil,2,İkinci El,"4,200,000TL",adalar,21 Ve Üzeri
21,6+1,682 m2,Müstakil,2,İkinci El,"4,200,000TL",adalar,21 Ve Üzeri
22,4+2,550 m2,3. Kat,3,İkinci El,"9,000,000TL",adalar,11-15
23,1 Oda,550 m2,Düz Giriş,2,NaN,"9,000,000TL",adalar,11-15
24,8+ Oda,2.250 m2,Düz Giriş,3,NaN,"21,000,000TL",adalar,21 Ve Üzeri
25,3+1,180 m2,2. Kat,3,İkinci El,"3,250,000TL",adalar,21 Ve Üzeri
26,2+1,100 m2,Bahçe Dublex,4,NaN,"515,000TL",arnavutkoy,2
27,4+2,200 m2,Çatı Dubleks,5,Sıfır,"1,000,000TL",arnavutkoy,0 (Yeni)
28,2+1,100 m2,Bahçe Dublex,5,İkinci El,"506,000TL",arnavutkoy,5-10
29,2+1,90 m2,1. Kat,4,NaN,"660,000TLarrow_downward%3",arnavutkoy,5-10
30,5+2,260 m2,Çatı Dubleks,5,NaN,"1,250,000TLarrow_downward%90",arnavutkoy,0 (Yeni)
31,2+1,100 m2,Bahçe Katı,5,NaN,"420,000TLarrow_downward%90",arnavutkoy,0 (Yeni)
32,4+1,180 m2,2. Kat,2,NaN,"765,000TL",arnavutkoy,0 (Yeni)
33,4+1,180 m2,2. Kat,2,NaN,"765,000TL",arnavutkoy,0 (Yeni)
34,1+1,85 m2,Yüksek Giriş,4,NaN,"480,000TL",arnavutkoy,3
35,2+1,105 m2,2. Kat,4,NaN,"715,000TL",arnavutkoy,4
36,3+2,160 m2,5. Kat,5,NaN,"850,000TL",arnavutkoy,0 (Yeni)
37,4+2,225 m2,Çatı Dubleks,5,NaN,"1,150,000TL",arnavutkoy,5-10
38,2+1,105 m2,5. Kat,5,İkinci El,"660,000TL",arnavutkoy,5-10
39,4+2,350 m2,Villa Tipi,4,İkinci El,"4,000,000TL",arnavutkoy,16-20
40,2+1,100 m2,2. Kat,5,NaN,"740,000TL",arnavutkoy,0 (Yeni)
41,2+1,100 m2,Düz Giriş,4,NaN,"625,000TL",arnavutkoy,0 (Yeni)
42,3+2,160 m2,5. Kat,5,NaN,"800,000TL",arnavutkoy,0 (Yeni)
43,2+1,95 m2,2. Kat,5,NaN,"590,000TL",arnavutkoy,0 (Yeni)
44,2+1,95 m2,2. Kat,4,NaN,"650,000TL",arnavutkoy,0 (Yeni)
45,2+1,90 m2,Bahçe Dublex,6,NaN,"850,000TL",arnavutkoy,5-10
46,2+1,350 m2,Müstakil,1,İkinci El,"1,150,000TL",arnavutkoy,11-15
47,5+2,330 m2,Düz Giriş,3,NaN,"5,800,000TL",arnavutkoy,11-15
48,2+1,100 m2,Bahçe Katı,4,NaN,"420,000TL",arnavutkoy,0 (Yeni)
49,2+1,100 m2,1. Kat,5,NaN,"735,000TL",arnavutkoy,0 (Yeni)